package com.glowmart.shop_management.common;

import com.glowmart.shop_management.dto.ProductDto;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.UUID;

/**
 * A utility class that provides common validation and helper functions
 * used across the application.
 * <p>
 * This class includes methods for validating user input (names, IDs, prices),
 * calculating discounts, and handling file uploads.
 * </p>
 */
public class CommonFunction {

    /**
     * Validates a name string.
     * <p>
     * The name must not be null or empty, must not consist only of digits,
     * and must contain only letters and spaces (no special characters).
     * </p>
     *
     * @param name the name string to validate
     * @return {@code true} if the name is valid, {@code false} otherwise
     */
    public static boolean isValidName(String name){
        if (name == null || name.trim().isEmpty()){
            return false;
        }
        /*Check if it's only digits*/
        if (name.matches("\\d+")) {
            return false;
        }
        /*Check if it contains only letters and spaces (no special characters)*/
        if (!name.matches("[a-zA-Z ]+")) {
            return false;
        }
        return true;
    }

    /**
     * Validates an ID string.
     * <p>
     * The ID must not be null or empty, must contain only digits,
     * and must represent a positive number.
     * </p>
     *
     * @param input the ID string to validate
     * @return {@code true} if the ID is valid, {@code false} otherwise
     */
    public static boolean isValidId(String input){
        if (input == null || input.trim().isEmpty()){
            return false;
        }
        // Check if input contains only digits
        if (!input.matches("\\d+")) {
            return false;
        }
        try {
            Long id = Long.parseLong(input);
            return id > 0;
        } catch (NumberFormatException e){
            return false;
        }
    }

    /**
     * Validates product price and discount percentage.
     * <p>
     * The original price must be greater than zero, and the discount percentage
     * must be between 0 and 100 inclusive.
     * </p>
     *
     * @param originalPrice      the original product price
     * @param discountPercentage the discount percentage to apply
     * @return {@code true} if both values are valid, {@code false} otherwise
     */
    public static boolean isValidPriceAndDiscount(Double originalPrice, Double discountPercentage){
        if ((originalPrice != null && originalPrice > 0)
                && (discountPercentage != null && discountPercentage >= 0 && discountPercentage <= 100)){
            return true;
        } else {
            return false;
        }
    }

    /**
     * Calculates the discount amount based on the original price and discount percentage.
     *
     * @param originalPrice      the original product price
     * @param discountPercentage the discount percentage to apply
     * @return the calculated discount amount
     */
    public static Double calculateDiscountAmount(Double originalPrice, Double discountPercentage){
        return originalPrice * (discountPercentage / 100);
    }

    /**
     * Creates and saves a file to the "uploads" directory.
     * <p>
     * The file is saved with a unique name generated by combining a UUID
     * with the original filename. If the "uploads" directory does not exist,
     * it will be created automatically.
     * </p>
     *
     * @param file       the multipart file to save
     * @param productDto the product DTO associated with the file (currently unused)
     * @return the generated unique filename
     * @throws IOException if an I/O error occurs while saving the file
     */
    public static String createFile(MultipartFile file, ProductDto productDto) throws IOException {
        /*Create uploads directory if not exists*/
        String fileName = UUID.randomUUID() + "_" + file.getOriginalFilename();
        Path uploadPath = Paths.get("uploads");
        if (Files.notExists(uploadPath)) {
            Files.createDirectories(uploadPath);
        }

        /*Save file*/
        Path filePath = uploadPath.resolve(fileName);
        Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);
        return fileName;
    }

}