package com.glowmart.shop_management.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a category in the shopping system.
 * <p>
 * This entity is used to group products under specific categories.
 * Each category has a unique identifier, a name, and timestamps for tracking creation and updates.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
public class Category {

    /**
     * Unique identifier for the category.
     * <p>
     * This field is automatically generated by the database when a new category is created.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long categoryId;

    /**
     * The name of the category.
     * <p>
     * This field is required and cannot be null.
     * It represents the name of the product category (e.g., "Electronics", "Clothing").
     * </p>
     */
    @Column(nullable = false)
    private String categoryName;

    /**
     * Timestamp indicating when the category was created.
     * <p>
     * This field is automatically set when the category is created and cannot be updated.
     * </p>
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private LocalDateTime createdAt;

    /**
     * Timestamp indicating when the category was last updated.
     * <p>
     * This field is optional and is set when the category entity is updated.
     * </p>
     */
    @Column(nullable = true, columnDefinition = "TIMESTAMP DEFAULT NULL")
    private LocalDateTime updatedAt;

}
