package com.glowmart.shop_management.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a payment method in the shopping system.
 * <p>
 * This entity stores details about different payment methods available for transactions,
 * including their name, description, and timestamps for creation, updates, and deletion.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
public class PaymentMethod {

    /**
     * Unique identifier for the payment method.
     * <p>
     * This field is automatically generated by the database when a new payment method is created.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentMethodId;

    /**
     * The name of the payment method.
     * <p>
     * This field is required and has a maximum length of 50 characters.
     * </p>
     */
    @Column(nullable = false, length = 50)
    private String paymentMethodName;

    /**
     * A detailed description of the payment method.
     * <p>
     * This field is required and provides additional information about the payment method.
     * </p>
     */
    @Column(nullable = false)
    private String paymentMethodDescription;

    /**
     * Timestamp indicating when the payment method was created.
     * <p>
     * This field is automatically set when the payment method is created and cannot be updated.
     * </p>
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private LocalDateTime createdAt;

    /**
     * Timestamp indicating when the payment method was last updated.
     * <p>
     * This field is optional and is set when the payment method details are modified.
     * </p>
     */
    @Column(nullable = true, columnDefinition = "TIMESTAMP DEFAULT NULL")
    private LocalDateTime updatedAt;

    /**
     * Timestamp indicating when the payment method was deleted.
     * <p>
     * This field is optional and is set when the payment method is removed from the system.
     * </p>
     */
    @Column(nullable = true, columnDefinition = "TIMESTAMP DEFAULT NULL")
    private LocalDateTime deletedAt;
}
