package com.glowmart.shop_management.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.Set;

/**
 * Represents a permission entity in the system.
 * <p>
 * This entity defines the permissions that can be assigned to roles.
 * Each permission can be linked to multiple roles.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Permission {

    /**
     * Unique identifier for the permission.
     * <p>
     * This field is automatically generated by the database when a new permission is created.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long permissionId;

    /**
     * The name of the permission.
     * <p>
     * This field is required and represents the specific action or access right granted.
     * </p>
     */
    @Column(nullable = false)
    private String permissionName;

    /**
     * The set of roles associated with this permission.
     * <p>
     * This is a many-to-many relationship, meaning a permission can be assigned to multiple roles,
     * and a role can have multiple permissions.
     * </p>
     */
    @ManyToMany(mappedBy = "permissions")
    private Set<Role> roles;

    /**
     * Timestamp for when the permission was created.
     * <p>
     * This field is automatically set when the permission is created and cannot be updated.
     * </p>
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private LocalDateTime createdAt;
}
