package com.glowmart.shop_management.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * Represents a refresh token in the authentication system.
 * <p>
 * This entity stores refresh tokens that are issued to users during login.
 * Refresh tokens are used to obtain new access tokens without requiring
 * the user to re-authenticate. Each token is associated with a specific user
 * and has an expiration date to ensure security.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "refresh_tokens")
public class RefreshToken {

    /**
     * Unique identifier for the refresh token.
     * <p>
     * This field is automatically generated by the database when a new token is created.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The username associated with the refresh token.
     * <p>
     * This field links the token to the user who owns it.
     * </p>
     */
    private String userName;

    /**
     * The actual refresh token string.
     * <p>
     * This value is unique and required. It is used to validate requests
     * for new access tokens.
     * </p>
     */
    @Column(unique = true, nullable = false)
    private String token;

    /**
     * The expiration date and time of the refresh token.
     * <p>
     * After this timestamp, the token becomes invalid and cannot be used
     * to generate new access tokens.
     * </p>
     */
    private Instant expireDate;
}
